<a href="https://colab.research.google.com/github/tushar-sharma-119/tushar-python/blob/main/day_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# filter
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr>20] # filter
print(arr_f)


[ 90 200]


In [ ]:
import numpy as np
arr = np.array([10,20,30,6,3,2])
arr_f = arr[arr!=6] # filter
print(arr_f)

[10 20 30  3  2]


In [ ]:
arr = np.array([10,20,30,15,17,6,3,2])
arr_f= arr[(arr>10) & (arr<20)]
print(arr_f)

[15 17]


In [ ]:
#fancing indexing
import numpy as np
arr = np.array([10,20,30,3,4,90,100])
print(arr)
arr_f = arr[[0,2]]
print(arr_f)

[ 10  20  30   3   4  90 100]
[10 30]


In [ ]:
import numpy as np
arr = np.array([10,20,30,3,4,90,100])
print(arr)
arr_w = np.where(arr>9,"true","false")
print(arr_w)


[ 10  20  30   3   4  90 100]
['true' 'true' 'true' 'false' 'false' 'true' 'true']


In [ ]:
arr = np.array([10,20,30,3,4,90,100])
print(arr)
arr_w = np.where((arr>10)&(arr>20),arr*2,arr+2)
print(arr_w)


[ 10  20  30   3   4  90 100]
[ 12  22  60   5   6 180 200]


In [ ]:
arr = np.array([1,2,3,3,4,9,])
print(np.sum(arr))

22


In [ ]:
arr= np.array([3,2,6,4,10])
print(np.mean(arr))

5.0


In [ ]:
arr= np.array([1,3,2,6,4,10])
print(np.mode(arr))

AttributeError: module 'numpy' has no attribute 'mode'

In [ ]:
# data structure: [restaurent_id'2021,2022,2023,2024]
import numpy as np

sales_data = np.array([
    [1,150000,180000,220000,250000],# paradise biryani
    [2,120000,140000,160000,190000],# beijing bites
    [3,200000,230000,260000,300000],# pizza hub
    [4,180000,210000,240000,270000],# buger point
    [5,160000,185000,205000,230000],# chai point
])

print(sales_data)
print(sales_data.shape)
print("dimension:",sales_data.ndim)
print("total elements:",sales_data.size)
print("restaurent_id:",sales_data[:,0])
print("2021 sales:",sales_data[:,1])
print("2024 sales:",sales_data[:,4])
print(np.max(sales_data[:,1:]))
print(np.min(sales_data[:,1:]))
print("\ntotal 2021 sales:",np.sum(sales_data[:,1]))
print("\ntotal 2024 sales:",np.mean(sales_data[:,4]))
print(np.sum(sales_data[:,1:], axis=1))
print(np.mean(sales_data[:,1:], axis=1))

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
(5, 5)
dimension: 2
total elements: 25
restaurent_id: [1 2 3 4 5]
2021 sales: [150000 120000 200000 180000 160000]
2024 sales: [250000 190000 300000 270000 230000]
300000
120000

total 2021 sales: 810000

total 2024 sales: 248000.0
[800000 610000 990000 900000 780000]
[200000. 152500. 247500. 225000. 195000.]
